language: python
python:
    - "2.7"
    - "3.6"
before_install:
    # Without this old versions of pip can fail to install NumPy.
    - pip install -U pip
install:
    - pip install python-coveralls
    - pip install -r requirements.txt
script:
    - nosetests --with-coverage --cover-package=projectTemplate
after_success:
    - coveralls